// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class Action {
    "task": string;
    "owner": string;
    "due": string;
    "done": boolean;

    /** Creates a new Action instance. */
    constructor($$source: Partial<Action> = {}) {
        if (!("task" in $$source)) {
            this["task"] = "";
        }
        if (!("owner" in $$source)) {
            this["owner"] = "";
        }
        if (!("due" in $$source)) {
            this["due"] = "";
        }
        if (!("done" in $$source)) {
            this["done"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Action instance from a string or object.
     */
    static createFrom($$source: any = {}): Action {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Action($$parsedSource as Partial<Action>);
    }
}

/**
 * Analytics is what the shape of a meeting looks like from outside the words:
 * who held the floor, for how long, how fast, and who was actually asking
 * things rather than telling.
 *
 * Computed from the stored rows every time it is asked for rather than saved.
 * It is a walk over a few hundred turns, it can never go stale, and it follows
 * a speaker being renamed without a migration.
 */
export class Analytics {
    /**
     * seconds anybody was talking
     */
    "speech": number;

    /**
     * seconds nobody was
     */
    "silence": number;

    /**
     * seconds two people were, at once
     */
    "overlap": number;

    /**
     * in the whole meeting
     */
    "words": number;

    /**
     * words per minute while somebody was talking
     */
    "pace": number;

    /**
     * most talkative first
     */
    "speakers": Voice[];

    /**
     * 0 = one person spoke, 1 = everyone equally
     */
    "balance": number;

    /**
     * the densest stretches, for the shape of the hour
     */
    "busiest": Moment[];

    /** Creates a new Analytics instance. */
    constructor($$source: Partial<Analytics> = {}) {
        if (!("speech" in $$source)) {
            this["speech"] = 0;
        }
        if (!("silence" in $$source)) {
            this["silence"] = 0;
        }
        if (!("overlap" in $$source)) {
            this["overlap"] = 0;
        }
        if (!("words" in $$source)) {
            this["words"] = 0;
        }
        if (!("pace" in $$source)) {
            this["pace"] = 0;
        }
        if (!("speakers" in $$source)) {
            this["speakers"] = [];
        }
        if (!("balance" in $$source)) {
            this["balance"] = 0;
        }
        if (!("busiest" in $$source)) {
            this["busiest"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Analytics instance from a string or object.
     */
    static createFrom($$source: any = {}): Analytics {
        const $$createField5_0 = $$createType1;
        const $$createField7_0 = $$createType3;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("speakers" in $$parsedSource) {
            $$parsedSource["speakers"] = $$createField5_0($$parsedSource["speakers"]);
        }
        if ("busiest" in $$parsedSource) {
            $$parsedSource["busiest"] = $$createField7_0($$parsedSource["busiest"]);
        }
        return new Analytics($$parsedSource as Partial<Analytics>);
    }
}

/**
 * Briefing is the answer to the two questions somebody actually opens this app
 * with: what did I miss, and what did I say I would do.
 *
 * Everything here is read out of summaries that were already written. No model
 * is called, nothing is sent anywhere, and it is the same few hundred rows the
 * Library screen reads — so it is instant and it works with no key.
 */
export class Briefing {
    "since": string;

    /**
     * in the window, newest first
     */
    "meetings": Recording[];

    /**
     * spent in them
     */
    "minutes": number;

    /**
     * what was settled, with where
     */
    "decided": Said[];

    /**
     * still open, oldest first
     */
    "mine": Outstanding[];

    /**
     * open, and their deadline has passed
     */
    "overdue": Outstanding[];

    /**
     * asked in more than one meeting and still open
     */
    "nagging": Nagging[];

    /**
     * who was in them
     */
    "voices": string[];

    /** Creates a new Briefing instance. */
    constructor($$source: Partial<Briefing> = {}) {
        if (!("since" in $$source)) {
            this["since"] = "0001-01-01T00:00:00.000Z";
        }
        if (!("meetings" in $$source)) {
            this["meetings"] = [];
        }
        if (!("minutes" in $$source)) {
            this["minutes"] = 0;
        }
        if (!("decided" in $$source)) {
            this["decided"] = [];
        }
        if (!("mine" in $$source)) {
            this["mine"] = [];
        }
        if (!("overdue" in $$source)) {
            this["overdue"] = [];
        }
        if (!("nagging" in $$source)) {
            this["nagging"] = [];
        }
        if (!("voices" in $$source)) {
            this["voices"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Briefing instance from a string or object.
     */
    static createFrom($$source: any = {}): Briefing {
        const $$createField1_0 = $$createType5;
        const $$createField3_0 = $$createType7;
        const $$createField4_0 = $$createType9;
        const $$createField5_0 = $$createType9;
        const $$createField6_0 = $$createType11;
        const $$createField7_0 = $$createType12;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("meetings" in $$parsedSource) {
            $$parsedSource["meetings"] = $$createField1_0($$parsedSource["meetings"]);
        }
        if ("decided" in $$parsedSource) {
            $$parsedSource["decided"] = $$createField3_0($$parsedSource["decided"]);
        }
        if ("mine" in $$parsedSource) {
            $$parsedSource["mine"] = $$createField4_0($$parsedSource["mine"]);
        }
        if ("overdue" in $$parsedSource) {
            $$parsedSource["overdue"] = $$createField5_0($$parsedSource["overdue"]);
        }
        if ("nagging" in $$parsedSource) {
            $$parsedSource["nagging"] = $$createField6_0($$parsedSource["nagging"]);
        }
        if ("voices" in $$parsedSource) {
            $$parsedSource["voices"] = $$createField7_0($$parsedSource["voices"]);
        }
        return new Briefing($$parsedSource as Partial<Briefing>);
    }
}

export class Chapter {
    "start": number;
    "title": string;
    "summary": string;

    /** Creates a new Chapter instance. */
    constructor($$source: Partial<Chapter> = {}) {
        if (!("start" in $$source)) {
            this["start"] = 0;
        }
        if (!("title" in $$source)) {
            this["title"] = "";
        }
        if (!("summary" in $$source)) {
            this["summary"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Chapter instance from a string or object.
     */
    static createFrom($$source: any = {}): Chapter {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Chapter($$parsedSource as Partial<Chapter>);
    }
}

/**
 * Hit is one passage that matched a search.
 */
export class Hit {
    "recording": number;
    "title": string;
    "start": number;
    "speaker"?: string;
    "text": string;

    /** Creates a new Hit instance. */
    constructor($$source: Partial<Hit> = {}) {
        if (!("recording" in $$source)) {
            this["recording"] = 0;
        }
        if (!("title" in $$source)) {
            this["title"] = "";
        }
        if (!("start" in $$source)) {
            this["start"] = 0;
        }
        if (!("text" in $$source)) {
            this["text"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Hit instance from a string or object.
     */
    static createFrom($$source: any = {}): Hit {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Hit($$parsedSource as Partial<Hit>);
    }
}

/**
 * Kind is what a recording turned out to be.
 */
export enum Kind {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    /**
     * somebody else was talking: diarized
     */
    Meeting = "meeting",

    /**
     * thinking aloud
     */
    Note = "note",
};

/**
 * A Moment is one slice of the timeline and how much was said in it, so the
 * meeting can be drawn as a shape rather than a list.
 */
export class Moment {
    "at": number;
    "words": number;

    /** Creates a new Moment instance. */
    constructor($$source: Partial<Moment> = {}) {
        if (!("at" in $$source)) {
            this["at"] = 0;
        }
        if (!("words" in $$source)) {
            this["words"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Moment instance from a string or object.
     */
    static createFrom($$source: any = {}): Moment {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Moment($$parsedSource as Partial<Moment>);
    }
}

/**
 * Nagging is a question that keeps coming back.
 *
 * This is the thing a pile of transcripts knows and a person does not: the same
 * thing was left unresolved in three meetings, and nobody noticed because each
 * meeting only remembers itself.
 */
export class Nagging {
    "text": string;
    "times": number;
    "said": Said[];

    /** Creates a new Nagging instance. */
    constructor($$source: Partial<Nagging> = {}) {
        if (!("text" in $$source)) {
            this["text"] = "";
        }
        if (!("times" in $$source)) {
            this["times"] = 0;
        }
        if (!("said" in $$source)) {
            this["said"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Nagging instance from a string or object.
     */
    static createFrom($$source: any = {}): Nagging {
        const $$createField2_0 = $$createType7;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("said" in $$parsedSource) {
            $$parsedSource["said"] = $$createField2_0($$parsedSource["said"]);
        }
        return new Nagging($$parsedSource as Partial<Nagging>);
    }
}

/**
 * Outstanding is every action item from every meeting, newest meeting first.
 * The inbox that answers "what did I commit to", which no single transcript can.
 */
export class Outstanding {
    "recording": number;
    "title": string;
    "started": string;
    "index": number;
    "task": string;
    "owner": string;
    "due": string;
    "done": boolean;

    /** Creates a new Outstanding instance. */
    constructor($$source: Partial<Outstanding> = {}) {
        if (!("recording" in $$source)) {
            this["recording"] = 0;
        }
        if (!("title" in $$source)) {
            this["title"] = "";
        }
        if (!("started" in $$source)) {
            this["started"] = "0001-01-01T00:00:00.000Z";
        }
        if (!("index" in $$source)) {
            this["index"] = 0;
        }
        if (!("task" in $$source)) {
            this["task"] = "";
        }
        if (!("owner" in $$source)) {
            this["owner"] = "";
        }
        if (!("due" in $$source)) {
            this["due"] = "";
        }
        if (!("done" in $$source)) {
            this["done"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Outstanding instance from a string or object.
     */
    static createFrom($$source: any = {}): Outstanding {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Outstanding($$parsedSource as Partial<Outstanding>);
    }
}

/**
 * A Person is somebody the app has been told the name of, and the voiceprints
 * it has collected for them since.
 */
export class Person {
    "id": number;
    "name": string;
    "samples": number;
    "meetings": number;

    /** Creates a new Person instance. */
    constructor($$source: Partial<Person> = {}) {
        if (!("id" in $$source)) {
            this["id"] = 0;
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("samples" in $$source)) {
            this["samples"] = 0;
        }
        if (!("meetings" in $$source)) {
            this["meetings"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Person instance from a string or object.
     */
    static createFrom($$source: any = {}): Person {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Person($$parsedSource as Partial<Person>);
    }
}

/**
 * Recording is one meeting or note.
 */
export class Recording {
    "id": number;
    "kind": Kind;

    /**
     * from the summary; the file name until then
     */
    "title": string;

    /**
     * file name under recordings/, empty once deleted
     */
    "audio": string;
    "started": string;
    "duration": number;
    "language": string;
    "status": Status;
    "progress": number;
    "problem"?: string;
    "summary"?: Summary | null;
    "speakers"?: string[];
    "turns": number;
    "note"?: string;

    /** Creates a new Recording instance. */
    constructor($$source: Partial<Recording> = {}) {
        if (!("id" in $$source)) {
            this["id"] = 0;
        }
        if (!("kind" in $$source)) {
            this["kind"] = Kind.$zero;
        }
        if (!("title" in $$source)) {
            this["title"] = "";
        }
        if (!("audio" in $$source)) {
            this["audio"] = "";
        }
        if (!("started" in $$source)) {
            this["started"] = "0001-01-01T00:00:00.000Z";
        }
        if (!("duration" in $$source)) {
            this["duration"] = 0;
        }
        if (!("language" in $$source)) {
            this["language"] = "";
        }
        if (!("status" in $$source)) {
            this["status"] = Status.$zero;
        }
        if (!("progress" in $$source)) {
            this["progress"] = 0;
        }
        if (!("turns" in $$source)) {
            this["turns"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Recording instance from a string or object.
     */
    static createFrom($$source: any = {}): Recording {
        const $$createField10_0 = $$createType14;
        const $$createField11_0 = $$createType12;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("summary" in $$parsedSource) {
            $$parsedSource["summary"] = $$createField10_0($$parsedSource["summary"]);
        }
        if ("speakers" in $$parsedSource) {
            $$parsedSource["speakers"] = $$createField11_0($$parsedSource["speakers"]);
        }
        return new Recording($$parsedSource as Partial<Recording>);
    }
}

/**
 * Said is one line from a summary, and the meeting it came from.
 */
export class Said {
    "recording": number;
    "title": string;
    "started": string;
    "text": string;

    /** Creates a new Said instance. */
    constructor($$source: Partial<Said> = {}) {
        if (!("recording" in $$source)) {
            this["recording"] = 0;
        }
        if (!("title" in $$source)) {
            this["title"] = "";
        }
        if (!("started" in $$source)) {
            this["started"] = "0001-01-01T00:00:00.000Z";
        }
        if (!("text" in $$source)) {
            this["text"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Said instance from a string or object.
     */
    static createFrom($$source: any = {}): Said {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Said($$parsedSource as Partial<Said>);
    }
}

/**
 * Status is where a recording is in the pipeline. Every one of these is shown
 * to the person waiting, because a recording that stops moving has to say where.
 */
export enum Status {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    Queued = "queued",
    Transcribing = "transcribing",
    Summarising = "summarising",
    Done = "done",
    Failed = "failed",
};

/**
 * Summary is stored as JSON; the shape belongs to the insights package, and this
 * is deliberately a loose mirror so the two can move independently.
 */
export class Summary {
    "title": string;
    "overview": string;
    "chapters": Chapter[];
    "topics": string[];
    "decisions": string[];
    "action_items": Action[];
    "open_questions": string[];

    /** Creates a new Summary instance. */
    constructor($$source: Partial<Summary> = {}) {
        if (!("title" in $$source)) {
            this["title"] = "";
        }
        if (!("overview" in $$source)) {
            this["overview"] = "";
        }
        if (!("chapters" in $$source)) {
            this["chapters"] = [];
        }
        if (!("topics" in $$source)) {
            this["topics"] = [];
        }
        if (!("decisions" in $$source)) {
            this["decisions"] = [];
        }
        if (!("action_items" in $$source)) {
            this["action_items"] = [];
        }
        if (!("open_questions" in $$source)) {
            this["open_questions"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Summary instance from a string or object.
     */
    static createFrom($$source: any = {}): Summary {
        const $$createField2_0 = $$createType16;
        const $$createField3_0 = $$createType12;
        const $$createField4_0 = $$createType12;
        const $$createField5_0 = $$createType18;
        const $$createField6_0 = $$createType12;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("chapters" in $$parsedSource) {
            $$parsedSource["chapters"] = $$createField2_0($$parsedSource["chapters"]);
        }
        if ("topics" in $$parsedSource) {
            $$parsedSource["topics"] = $$createField3_0($$parsedSource["topics"]);
        }
        if ("decisions" in $$parsedSource) {
            $$parsedSource["decisions"] = $$createField4_0($$parsedSource["decisions"]);
        }
        if ("action_items" in $$parsedSource) {
            $$parsedSource["action_items"] = $$createField5_0($$parsedSource["action_items"]);
        }
        if ("open_questions" in $$parsedSource) {
            $$parsedSource["open_questions"] = $$createField6_0($$parsedSource["open_questions"]);
        }
        return new Summary($$parsedSource as Partial<Summary>);
    }
}

/**
 * Turn is one row of a transcript.
 */
export class Turn {
    "start": number;
    "end": number;
    "speaker"?: string;
    "text": string;

    /** Creates a new Turn instance. */
    constructor($$source: Partial<Turn> = {}) {
        if (!("start" in $$source)) {
            this["start"] = 0;
        }
        if (!("end" in $$source)) {
            this["end"] = 0;
        }
        if (!("text" in $$source)) {
            this["text"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Turn instance from a string or object.
     */
    static createFrom($$source: any = {}): Turn {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Turn($$parsedSource as Partial<Turn>);
    }
}

/**
 * A Voice is one person's share of a meeting.
 */
export class Voice {
    "speaker": string;
    "seconds": number;
    "share": number;
    "turns": number;

    /**
     * their longest single stretch
     */
    "longest": number;
    "words": number;

    /**
     * their own words per minute
     */
    "pace": number;

    /**
     * turns of theirs that asked something
     */
    "questions": number;

    /** Creates a new Voice instance. */
    constructor($$source: Partial<Voice> = {}) {
        if (!("speaker" in $$source)) {
            this["speaker"] = "";
        }
        if (!("seconds" in $$source)) {
            this["seconds"] = 0;
        }
        if (!("share" in $$source)) {
            this["share"] = 0;
        }
        if (!("turns" in $$source)) {
            this["turns"] = 0;
        }
        if (!("longest" in $$source)) {
            this["longest"] = 0;
        }
        if (!("words" in $$source)) {
            this["words"] = 0;
        }
        if (!("pace" in $$source)) {
            this["pace"] = 0;
        }
        if (!("questions" in $$source)) {
            this["questions"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Voice instance from a string or object.
     */
    static createFrom($$source: any = {}): Voice {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Voice($$parsedSource as Partial<Voice>);
    }
}

// Private type creation functions
const $$createType0 = Voice.createFrom;
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = Moment.createFrom;
const $$createType3 = $Create.Array($$createType2);
const $$createType4 = Recording.createFrom;
const $$createType5 = $Create.Array($$createType4);
const $$createType6 = Said.createFrom;
const $$createType7 = $Create.Array($$createType6);
const $$createType8 = Outstanding.createFrom;
const $$createType9 = $Create.Array($$createType8);
const $$createType10 = Nagging.createFrom;
const $$createType11 = $Create.Array($$createType10);
const $$createType12 = $Create.Array($Create.Any);
const $$createType13 = Summary.createFrom;
const $$createType14 = $Create.Nullable($$createType13);
const $$createType15 = Chapter.createFrom;
const $$createType16 = $Create.Array($$createType15);
const $$createType17 = Action.createFrom;
const $$createType18 = $Create.Array($$createType17);
