// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Meetings is the service the interface talks to.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as listen$0 from "../listen/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as store$0 from "../store/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function AcceptSummary(id: number, before: store$0.Summary | null, after: store$0.Summary | null): $CancellablePromise<void> {
    return $Call.ByID(3947130702, id, before, after);
}

/**
 * Actions is the to-do list across every meeting.
 */
export function Actions(includeDone: boolean): $CancellablePromise<store$0.Outstanding[]> {
    return $Call.ByID(4286214473, includeDone).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * Again transcribes a recording from scratch — after the speakers were named,
 * after the language was set, or after anything in the app that reads audio got
 * better.
 */
export function Again(id: number): $CancellablePromise<void> {
    return $Call.ByID(2388190674, id);
}

/**
 * Analytics is the shape of a meeting: who held the floor, how fast, who asked
 * the questions. Measured from the rows, so it follows a rename immediately.
 */
export function Analytics(id: number): $CancellablePromise<store$0.Analytics | null> {
    return $Call.ByID(2094126650, id).then(($result: any) => {
        return $$createType3($result);
    });
}

/**
 * Appearances is the projects somebody has been heard in, busiest first — the
 * answer to "where does this person actually turn up".
 */
export function Appearances(name: string): $CancellablePromise<store$0.Group[]> {
    return $Call.ByID(1939080865, name).then(($result: any) => {
        return $$createType5($result);
    });
}

/**
 * Ask answers a question from the transcripts.
 */
export function Ask(question: string): $CancellablePromise<$models.Answer | null> {
    return $Call.ByID(1500112095, question).then(($result: any) => {
        return $$createType7($result);
    });
}

export function AskKnowledge(question: string): $CancellablePromise<$models.KnowledgeAnswer | null> {
    return $Call.ByID(1254955373, question).then(($result: any) => {
        return $$createType9($result);
    });
}

/**
 * Bin is what has been deleted and not yet thrown away.
 */
export function Bin(): $CancellablePromise<store$0.Recording[]> {
    return $Call.ByID(820010799).then(($result: any) => {
        return $$createType11($result);
    });
}

/**
 * Brief is the first screen: what happened in the last few days, what was
 * settled, what is still owed, and what keeps being asked without an answer.
 */
export function Brief(days: number): $CancellablePromise<store$0.Briefing | null> {
    return $Call.ByID(690406538, days).then(($result: any) => {
        return $$createType13($result);
    });
}

/**
 * Delete forgets a meeting and its audio.
 */
export function Delete(id: number): $CancellablePromise<void> {
    return $Call.ByID(2789016269, id);
}

/**
 * DropGroup removes a group and leaves its recordings unfiled.
 */
export function DropGroup(id: number): $CancellablePromise<void> {
    return $Call.ByID(974174766, id);
}

export function EditAction(id: number, index: number, action: store$0.Action): $CancellablePromise<void> {
    return $Call.ByID(1423411092, id, index, action);
}

/**
 * EmptyBin destroys everything in it, audio and all.
 */
export function EmptyBin(): $CancellablePromise<string> {
    return $Call.ByID(1597412084);
}

/**
 * File puts a recording in a group, or takes it out of every group when the
 * group is zero.
 *
 * Filing it also moves that project's document on, so dragging a meeting onto a
 * tile updates the project there and then.
 */
export function File(recording: number, group: number): $CancellablePromise<void> {
    return $Call.ByID(4262653172, recording, group);
}

/**
 * Forget drops a person, which is how a name given to the wrong voice is undone.
 */
export function Forget(name: string): $CancellablePromise<void> {
    return $Call.ByID(3211396467, name);
}

/**
 * Groups are the folders in the Library: projects, clients, teams.
 */
export function Groups(): $CancellablePromise<store$0.Group[]> {
    return $Call.ByID(3017561026).then(($result: any) => {
        return $$createType5($result);
    });
}

/**
 * Import takes a file from anywhere, copies it into the recordings folder and
 * queues it. Copying rather than referencing: a library that breaks when
 * somebody tidies their Downloads folder is not a library.
 */
export function Import(path: string): $CancellablePromise<store$0.Recording | null> {
    return $Call.ByID(2393183823, path).then(($result: any) => {
        return $$createType14($result);
    });
}

/**
 * InGroup lists one group's recordings.
 */
export function InGroup(group: number): $CancellablePromise<store$0.Recording[]> {
    return $Call.ByID(2924641732, group).then(($result: any) => {
        return $$createType11($result);
    });
}

/**
 * Listener hands over the always-on recorder when it is ready.
 */
export function Listener(r: listen$0.Recorder | null): $CancellablePromise<void> {
    return $Call.ByID(1729818974, r);
}

/**
 * Listening is the state of the always-on recorder, polled by the window: a
 * wait with no name is a bug, and this is the longest wait in the app.
 */
export function Listening(): $CancellablePromise<listen$0.Status> {
    return $Call.ByID(2744938035).then(($result: any) => {
        return $$createType15($result);
    });
}

/**
 * Live is the transcript of the meeting happening right now, written utterance
 * by utterance while it runs.
 */
export function Live(): $CancellablePromise<listen$0.Line[]> {
    return $Call.ByID(2531093944).then(($result: any) => {
        return $$createType17($result);
    });
}

/**
 * Loose is how many recordings belong to no project.
 */
export function Loose(): $CancellablePromise<number> {
    return $Call.ByID(3074855652);
}

/**
 * Markdown renders a whole meeting for pasting somewhere else. Export as the
 * smallest thing that could work: one string, and the interface puts it on the
 * clipboard.
 */
export function Markdown(id: number): $CancellablePromise<string> {
    return $Call.ByID(1704503591, id);
}

/**
 * Moment is where in a recording something was said, so a line of the project
 * document opens the meeting at the second rather than at the top.
 */
export function Moment(recording: number, text: string): $CancellablePromise<number> {
    return $Call.ByID(1538936198, recording, text);
}

/**
 * NewGroup makes one, or hands back the one that already has that name.
 */
export function NewGroup(name: string): $CancellablePromise<store$0.Group> {
    return $Call.ByID(2951344047, name).then(($result: any) => {
        return $$createType4($result);
    });
}

export function Notes(recording: number, project: number): $CancellablePromise<store$0.Sticky[]> {
    return $Call.ByID(3870704023, recording, project).then(($result: any) => {
        return $$createType19($result);
    });
}

/**
 * Open is a whole meeting, ready to read.
 */
export function Open(id: number): $CancellablePromise<$models.Meeting | null> {
    return $Call.ByID(3169510906, id).then(($result: any) => {
        return $$createType21($result);
    });
}

/**
 * Paint gives a project a colour, or an empty string to go back to the one
 * derived from its name.
 */
export function Paint(id: number, colour: string): $CancellablePromise<void> {
    return $Call.ByID(2169964894, id, colour);
}

/**
 * PaintPerson gives somebody a colour, or an empty string to go back to the one
 * derived from their name.
 */
export function PaintPerson(name: string, colour: string): $CancellablePromise<void> {
    return $Call.ByID(1523618083, name, colour);
}

/**
 * People is everybody the app can now recognise by voice.
 */
export function People(): $CancellablePromise<store$0.Person[]> {
    return $Call.ByID(3465037041).then(($result: any) => {
        return $$createType23($result);
    });
}

/**
 * PinItem is a person editing a line of the project document; from then on the
 * model may close it but never reword it.
 */
export function PinItem(group: number, id: number, text: string, owner: string, due: string): $CancellablePromise<void> {
    return $Call.ByID(1162602530, group, id, text, owner, due);
}

/**
 * Playing tells the listener that the app's own player is running, so that
 * pressing play does not make the app record its own playback as a meeting.
 */
export function Playing(on: boolean): $CancellablePromise<void> {
    return $Call.ByID(1269014556, on);
}

export function PreviewSummary(id: number): $CancellablePromise<store$0.Summary | null> {
    return $Call.ByID(1815224778, id).then(($result: any) => {
        return $$createType25($result);
    });
}

export function PutNote(note: store$0.Sticky): $CancellablePromise<store$0.Sticky> {
    return $Call.ByID(4192976983, note).then(($result: any) => {
        return $$createType18($result);
    });
}

/**
 * RebuildProject replays every meeting into a fresh document. The answer to
 * "this has gone wrong".
 */
export function RebuildProject(group: number): $CancellablePromise<void> {
    return $Call.ByID(3236221742, group);
}

/**
 * Recent is the Library screen: what has been recorded, newest first.
 */
export function Recent(limit: number): $CancellablePromise<store$0.Recording[]> {
    return $Call.ByID(1420283577, limit).then(($result: any) => {
        return $$createType11($result);
    });
}

/**
 * Record is the button: start a recording now, or stop the one running. A
 * forced recording ignores silence, which is what makes it useful for a meeting
 * in a room where nothing comes out of the speakers.
 */
export function Record(): $CancellablePromise<void> {
    return $Call.ByID(2466039479);
}

/**
 * Redate says when a meeting really happened.
 *
 * It matters more than a label. The project document is built by replaying its
 * meetings oldest first, so a recording carrying the wrong date is read into
 * the project's history at the wrong point — a decision reversed in March lands
 * after the one that reversed it. Imported files guess from the file's own
 * timestamp, and this is how the guess is corrected.
 */
export function Redate(recording: number, when: string): $CancellablePromise<void> {
    return $Call.ByID(2426394395, recording, when);
}

/**
 * Reindex embeds every transcript that has no vectors yet, which is how
 * semantic search reaches the meetings recorded before a key was added.
 */
export function Reindex(): $CancellablePromise<string> {
    return $Call.ByID(2651234501);
}

export function RemoveNote(id: number): $CancellablePromise<void> {
    return $Call.ByID(2502196882, id);
}

/**
 * Rename changes a speaker's label throughout one meeting. The commonest edit
 * there is: SPEAKER_00 becomes Olena.
 * Renaming a speaker is also how the app learns a voice. That is the whole
 * point of doing it here rather than in a settings screen nobody visits: you
 * name somebody once, in the meeting where you recognised them, and from then
 * on they arrive already named.
 */
export function Rename(id: number, $from: string, to: string): $CancellablePromise<void> {
    return $Call.ByID(3355732220, id, $from, to);
}

/**
 * RenameGroup changes a project's name.
 */
export function RenameGroup(id: number, name: string): $CancellablePromise<void> {
    return $Call.ByID(3567885487, id, name);
}

/**
 * Restore takes a recording back out of the bin.
 */
export function Restore(id: number): $CancellablePromise<void> {
    return $Call.ByID(2469582744, id);
}

/**
 * Retitle is the user overruling the model's guess at what the hour was about.
 * From then on summarising again leaves the title alone.
 */
export function Retitle(id: number, title: string): $CancellablePromise<void> {
    return $Call.ByID(1977650231, id, title);
}

/**
 * RevealFolder opens ~/MeetingTranscriber in the file manager, which is the
 * answer to "where are my recordings".
 */
export function RevealFolder(): $CancellablePromise<void> {
    return $Call.ByID(4141902131);
}

/**
 * Samples is what the app thinks somebody sounds like: one entry per saved
 * voiceprint, naming the meeting and the longest thing they said in it.
 *
 * This is the answer to "why does it keep calling that person Olena" — the
 * evidence is playable instead of being 512 numbers nobody can argue with.
 */
export function Samples(name: string): $CancellablePromise<store$0.Source[]> {
    return $Call.ByID(1556926209, name).then(($result: any) => {
        return $$createType27($result);
    });
}

/**
 * SaveNote keeps what somebody typed against a meeting.
 */
export function SaveNote(id: number, note: string): $CancellablePromise<void> {
    return $Call.ByID(2773378063, id, note);
}

/**
 * SaveSettings writes them back. The key is the only thing here worth guarding,
 * and it goes to a file in the user's own folder and nowhere else.
 */
export function SaveSettings(s: $models.Settings): $CancellablePromise<void> {
    return $Call.ByID(1260496690, s);
}

/**
 * Search finds passages across every transcript.
 */
export function Search(query: string): $CancellablePromise<store$0.Hit[]> {
    return $Call.ByID(1634764442, query).then(($result: any) => {
        return $$createType29($result);
    });
}

export function SearchKnowledge(query: string, semantic: boolean): $CancellablePromise<store$0.KnowledgeHit[]> {
    return $Call.ByID(3922664222, query, semantic).then(($result: any) => {
        return $$createType31($result);
    });
}

export function Settings(): $CancellablePromise<$models.Settings> {
    return $Call.ByID(4203116247).then(($result: any) => {
        return $$createType32($result);
    });
}

/**
 * Span is every recording of the last `days` days, as the timeline draws them.
 */
export function Span(days: number): $CancellablePromise<store$0.Mark[]> {
    return $Call.ByID(3717387314, days).then(($result: any) => {
        return $$createType34($result);
    });
}

/**
 * Standing is where a project stands, gathered from its meetings.
 */
export function Standing(group: number): $CancellablePromise<store$0.Standing | null> {
    return $Call.ByID(1016657098, group).then(($result: any) => {
        return $$createType36($result);
    });
}

/**
 * Summaries reports whether there is a key to summarise and answer with. The
 * window asks so that it can say the feature is off rather than look broken.
 */
export function Summaries(): $CancellablePromise<boolean> {
    return $Call.ByID(2534345830);
}

/**
 * Summarise reads a meeting again — after a key was added, or after the
 * speakers were given names and the summary should use them.
 */
export function Summarise(id: number): $CancellablePromise<void> {
    return $Call.ByID(2369526854, id);
}

/**
 * ThisIsMe puts a name to the person holding the laptop.
 *
 * Everything the microphone hears is already one speaker, called "You" — so
 * this is the one enrolment the app can be certain about, and doing it once
 * makes every note and every one of your own turns carry your name from then
 * on. Any recording will do; the most recent one with a voiceprint is used.
 */
export function ThisIsMe(name: string): $CancellablePromise<string> {
    return $Call.ByID(821810460, name);
}

/**
 * Tick marks one action item done, or undone.
 */
export function Tick(id: number, index: number, done: boolean): $CancellablePromise<void> {
    return $Call.ByID(2083712087, id, index, done);
}

/**
 * TickItem ticks a line of the project document off, or puts it back.
 */
export function TickItem(group: number, id: number, done: boolean): $CancellablePromise<void> {
    return $Call.ByID(929529136, group, id, done);
}

/**
 * Tidy deletes audio older than the setting, now. The same sweep runs daily on
 * its own; this is the button for somebody who has just noticed the folder is
 * twelve gigabytes.
 */
export function Tidy(): $CancellablePromise<string> {
    return $Call.ByID(2386150514);
}

/**
 * Waveform is the loudness of a recording across its length, for the player to
 * draw. Read from the same folded copy the player is served, so what is on the
 * screen is what will be heard.
 */
export function Waveform(id: number): $CancellablePromise<number[]> {
    return $Call.ByID(1962206177, id).then(($result: any) => {
        return $$createType37($result);
    });
}

// Private type creation functions
const $$createType0 = store$0.Outstanding.createFrom;
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = store$0.Analytics.createFrom;
const $$createType3 = $Create.Nullable($$createType2);
const $$createType4 = store$0.Group.createFrom;
const $$createType5 = $Create.Array($$createType4);
const $$createType6 = $models.Answer.createFrom;
const $$createType7 = $Create.Nullable($$createType6);
const $$createType8 = $models.KnowledgeAnswer.createFrom;
const $$createType9 = $Create.Nullable($$createType8);
const $$createType10 = store$0.Recording.createFrom;
const $$createType11 = $Create.Array($$createType10);
const $$createType12 = store$0.Briefing.createFrom;
const $$createType13 = $Create.Nullable($$createType12);
const $$createType14 = $Create.Nullable($$createType10);
const $$createType15 = listen$0.Status.createFrom;
const $$createType16 = listen$0.Line.createFrom;
const $$createType17 = $Create.Array($$createType16);
const $$createType18 = store$0.Sticky.createFrom;
const $$createType19 = $Create.Array($$createType18);
const $$createType20 = $models.Meeting.createFrom;
const $$createType21 = $Create.Nullable($$createType20);
const $$createType22 = store$0.Person.createFrom;
const $$createType23 = $Create.Array($$createType22);
const $$createType24 = store$0.Summary.createFrom;
const $$createType25 = $Create.Nullable($$createType24);
const $$createType26 = store$0.Source.createFrom;
const $$createType27 = $Create.Array($$createType26);
const $$createType28 = store$0.Hit.createFrom;
const $$createType29 = $Create.Array($$createType28);
const $$createType30 = store$0.KnowledgeHit.createFrom;
const $$createType31 = $Create.Array($$createType30);
const $$createType32 = $models.Settings.createFrom;
const $$createType33 = store$0.Mark.createFrom;
const $$createType34 = $Create.Array($$createType33);
const $$createType35 = store$0.Standing.createFrom;
const $$createType36 = $Create.Nullable($$createType35);
const $$createType37 = $Create.Array($Create.Any);
