// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Meetings is the service the interface talks to.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as listen$0 from "../listen/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as store$0 from "../store/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * Actions is the to-do list across every meeting.
 */
export function Actions(includeDone: boolean): $CancellablePromise<store$0.Outstanding[]> {
    return $Call.ByID(4286214473, includeDone).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * Again transcribes a recording from scratch — after the speakers were named,
 * after the language was set, or after anything in the app that reads audio got
 * better.
 */
export function Again(id: number): $CancellablePromise<void> {
    return $Call.ByID(2388190674, id);
}

/**
 * Analytics is the shape of a meeting: who held the floor, how fast, who asked
 * the questions. Measured from the rows, so it follows a rename immediately.
 */
export function Analytics(id: number): $CancellablePromise<store$0.Analytics | null> {
    return $Call.ByID(2094126650, id).then(($result: any) => {
        return $$createType3($result);
    });
}

/**
 * Ask answers a question from the transcripts.
 */
export function Ask(question: string): $CancellablePromise<$models.Answer | null> {
    return $Call.ByID(1500112095, question).then(($result: any) => {
        return $$createType5($result);
    });
}

/**
 * Brief is the first screen: what happened in the last few days, what was
 * settled, what is still owed, and what keeps being asked without an answer.
 */
export function Brief(days: number): $CancellablePromise<store$0.Briefing | null> {
    return $Call.ByID(690406538, days).then(($result: any) => {
        return $$createType7($result);
    });
}

/**
 * Delete forgets a meeting and its audio.
 */
export function Delete(id: number): $CancellablePromise<void> {
    return $Call.ByID(2789016269, id);
}

/**
 * Forget drops a person, which is how a name given to the wrong voice is undone.
 */
export function Forget(name: string): $CancellablePromise<void> {
    return $Call.ByID(3211396467, name);
}

/**
 * Import takes a file from anywhere, copies it into the recordings folder and
 * queues it. Copying rather than referencing: a library that breaks when
 * somebody tidies their Downloads folder is not a library.
 */
export function Import(path: string): $CancellablePromise<store$0.Recording | null> {
    return $Call.ByID(2393183823, path).then(($result: any) => {
        return $$createType9($result);
    });
}

/**
 * Listener hands over the always-on recorder when it is ready.
 */
export function Listener(r: listen$0.Recorder | null): $CancellablePromise<void> {
    return $Call.ByID(1729818974, r);
}

/**
 * Listening is the state of the always-on recorder, polled by the window: a
 * wait with no name is a bug, and this is the longest wait in the app.
 */
export function Listening(): $CancellablePromise<listen$0.Status> {
    return $Call.ByID(2744938035).then(($result: any) => {
        return $$createType10($result);
    });
}

/**
 * Live is the transcript of the meeting happening right now, written utterance
 * by utterance while it runs.
 */
export function Live(): $CancellablePromise<listen$0.Line[]> {
    return $Call.ByID(2531093944).then(($result: any) => {
        return $$createType12($result);
    });
}

/**
 * Markdown renders a whole meeting for pasting somewhere else. Export as the
 * smallest thing that could work: one string, and the interface puts it on the
 * clipboard.
 */
export function Markdown(id: number): $CancellablePromise<string> {
    return $Call.ByID(1704503591, id);
}

/**
 * Open is a whole meeting, ready to read.
 */
export function Open(id: number): $CancellablePromise<$models.Meeting | null> {
    return $Call.ByID(3169510906, id).then(($result: any) => {
        return $$createType14($result);
    });
}

/**
 * People is everybody the app can now recognise by voice.
 */
export function People(): $CancellablePromise<store$0.Person[]> {
    return $Call.ByID(3465037041).then(($result: any) => {
        return $$createType16($result);
    });
}

/**
 * Recent is the Library screen: what has been recorded, newest first.
 */
export function Recent(limit: number): $CancellablePromise<store$0.Recording[]> {
    return $Call.ByID(1420283577, limit).then(($result: any) => {
        return $$createType17($result);
    });
}

/**
 * Record is the button: start a recording now, or stop the one running. A
 * forced recording ignores silence, which is what makes it useful for a meeting
 * in a room where nothing comes out of the speakers.
 */
export function Record(): $CancellablePromise<void> {
    return $Call.ByID(2466039479);
}

/**
 * Reindex embeds every transcript that has no vectors yet, which is how
 * semantic search reaches the meetings recorded before a key was added.
 */
export function Reindex(): $CancellablePromise<string> {
    return $Call.ByID(2651234501);
}

/**
 * Rename changes a speaker's label throughout one meeting. The commonest edit
 * there is: SPEAKER_00 becomes Olena.
 * Renaming a speaker is also how the app learns a voice. That is the whole
 * point of doing it here rather than in a settings screen nobody visits: you
 * name somebody once, in the meeting where you recognised them, and from then
 * on they arrive already named.
 */
export function Rename(id: number, $from: string, to: string): $CancellablePromise<void> {
    return $Call.ByID(3355732220, id, $from, to);
}

/**
 * RevealFolder opens ~/MeetingTranscriber in the file manager, which is the
 * answer to "where are my recordings".
 */
export function RevealFolder(): $CancellablePromise<void> {
    return $Call.ByID(4141902131);
}

/**
 * SaveNote keeps what somebody typed against a meeting.
 */
export function SaveNote(id: number, note: string): $CancellablePromise<void> {
    return $Call.ByID(2773378063, id, note);
}

/**
 * SaveSettings writes them back. The key is the only thing here worth guarding,
 * and it goes to a file in the user's own folder and nowhere else.
 */
export function SaveSettings(s: $models.Settings): $CancellablePromise<void> {
    return $Call.ByID(1260496690, s);
}

/**
 * Search finds passages across every transcript.
 */
export function Search(query: string): $CancellablePromise<store$0.Hit[]> {
    return $Call.ByID(1634764442, query).then(($result: any) => {
        return $$createType19($result);
    });
}

export function Settings(): $CancellablePromise<$models.Settings> {
    return $Call.ByID(4203116247).then(($result: any) => {
        return $$createType20($result);
    });
}

/**
 * Summaries reports whether there is a key to summarise and answer with. The
 * window asks so that it can say the feature is off rather than look broken.
 */
export function Summaries(): $CancellablePromise<boolean> {
    return $Call.ByID(2534345830);
}

/**
 * Summarise reads a meeting again — after a key was added, or after the
 * speakers were given names and the summary should use them.
 */
export function Summarise(id: number): $CancellablePromise<void> {
    return $Call.ByID(2369526854, id);
}

/**
 * ThisIsMe puts a name to the person holding the laptop.
 *
 * Everything the microphone hears is already one speaker, called "You" — so
 * this is the one enrolment the app can be certain about, and doing it once
 * makes every note and every one of your own turns carry your name from then
 * on. Any recording will do; the most recent one with a voiceprint is used.
 */
export function ThisIsMe(name: string): $CancellablePromise<string> {
    return $Call.ByID(821810460, name);
}

/**
 * Tick marks one action item done, or undone.
 */
export function Tick(id: number, index: number, done: boolean): $CancellablePromise<void> {
    return $Call.ByID(2083712087, id, index, done);
}

/**
 * Tidy deletes audio older than the setting, now. The same sweep runs daily on
 * its own; this is the button for somebody who has just noticed the folder is
 * twelve gigabytes.
 */
export function Tidy(): $CancellablePromise<string> {
    return $Call.ByID(2386150514);
}

// Private type creation functions
const $$createType0 = store$0.Outstanding.createFrom;
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = store$0.Analytics.createFrom;
const $$createType3 = $Create.Nullable($$createType2);
const $$createType4 = $models.Answer.createFrom;
const $$createType5 = $Create.Nullable($$createType4);
const $$createType6 = store$0.Briefing.createFrom;
const $$createType7 = $Create.Nullable($$createType6);
const $$createType8 = store$0.Recording.createFrom;
const $$createType9 = $Create.Nullable($$createType8);
const $$createType10 = listen$0.Status.createFrom;
const $$createType11 = listen$0.Line.createFrom;
const $$createType12 = $Create.Array($$createType11);
const $$createType13 = $models.Meeting.createFrom;
const $$createType14 = $Create.Nullable($$createType13);
const $$createType15 = store$0.Person.createFrom;
const $$createType16 = $Create.Array($$createType15);
const $$createType17 = $Create.Array($$createType8);
const $$createType18 = store$0.Hit.createFrom;
const $$createType19 = $Create.Array($$createType18);
const $$createType20 = $models.Settings.createFrom;
