// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as store$0 from "../store/models.js";

/**
 * Kind is what a recording turned out to be — the store's own type, because
 * that is where it ends up and a second copy of two constants would be two
 * copies to keep in step.
 */
export type Kind = store$0.Kind;

/**
 * A Line is one utterance, written down.
 */
export class Line {
    /**
     * seconds into the recording
     */
    "at": number;

    /**
     * "you" or "them" — which channel it came from
     */
    "who": string;
    "text": string;

    /** Creates a new Line instance. */
    constructor($$source: Partial<Line> = {}) {
        if (!("at" in $$source)) {
            this["at"] = 0;
        }
        if (!("who" in $$source)) {
            this["who"] = "";
        }
        if (!("text" in $$source)) {
            this["text"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Line instance from a string or object.
     */
    static createFrom($$source: any = {}): Line {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Line($$parsedSource as Partial<Line>);
    }
}

/**
 * Phase is what the app is doing, for the window to show. Every wait is a
 * visible state; a pause with no name is a bug.
 */
export enum Phase {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    /**
     * listening is switched off in the settings
     */
    Off = "off",

    /**
     * waiting for the devices, and often for a permission dialog
     */
    Opening = "opening",
    Listening = "listening",
    Recording = "recording",

    /**
     * it has gone quiet, and this may be the end
     */
    WrappingUp = "wrapping up",
    Paused = "paused",
    Broken = "broken",
};

/**
 * Recorder is the whole loop: audio in, finished recordings out.
 */
export class Recorder {

    /** Creates a new Recorder instance. */
    constructor($$source: Partial<Recorder> = {}) {

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Recorder instance from a string or object.
     */
    static createFrom($$source: any = {}): Recorder {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Recorder($$parsedSource as Partial<Recorder>);
    }
}

/**
 * Status is the snapshot the window polls.
 */
export class Status {
    "phase": Phase;
    "kind": Kind;

    /**
     * seconds of the current recording
     */
    "elapsed": number;

    /**
     * seconds since anybody last spoke
     */
    "quiet": number;

    /**
     * is the other side being captured at all
     */
    "system": boolean;
    "problem": string;

    /** Creates a new Status instance. */
    constructor($$source: Partial<Status> = {}) {
        if (!("phase" in $$source)) {
            this["phase"] = Phase.$zero;
        }
        if (!("kind" in $$source)) {
            this["kind"] = store$0.Kind.$zero;
        }
        if (!("elapsed" in $$source)) {
            this["elapsed"] = 0;
        }
        if (!("quiet" in $$source)) {
            this["quiet"] = 0;
        }
        if (!("system" in $$source)) {
            this["system"] = false;
        }
        if (!("problem" in $$source)) {
            this["problem"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Status instance from a string or object.
     */
    static createFrom($$source: any = {}): Status {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Status($$parsedSource as Partial<Status>);
    }
}
